/* DataBase is where data is stored for future use */
-- SQL is the structured Query Language that the database understand--
--DBMS( Database Management System manage the query sent to the database
-- Types of SQL
		 -- Data Query Language 
		 -- Data Definition Language
		 -- Data Manipulaton Language
		 -- Data Control Language
-- Data Query Language 
  -- Select--
SELECT * 
  FROM SALES.CUSTOMERS
  WHERE COUNTRY = 'GERMANY'
  ORDER BY SCORE DESC; 
-- DATA DEFINITION LANGUAGE
 -- CREATE, ALTER , DROP, INSERT, UPDATE, DELETE, MERGE, TRUNCATE --
   -- CREATE--
CREATE TABLE OLAWALE (
ID INT PRIMARY KEY,
FIRST_NAME VARCHAR(50) NOT NULL,  -- CREATE TABLE
LAST_NAME VARCHAR(50) NOT NULL,
AGE INT,
DOB DATE)
SELECT * 
	FROM OLAWALE
	-- ALTER--
ALTER TABLE OLAWALE
	ADD OCCUPATION VARCHAR (50)
ALTER TABLE OLAWALE
  DROP COLUMN OCCUPATION
  --INSERT--
  INSERT INTO OLAWALE (ID, FIRST_NAME, LAST_NAME, AGE, DOB)
  VALUES(1,'RAJI','ISMAILA',34, '1999-04-04'),
		(2,'ADAM','OLALEKAN',45,'1998-04-02'),
		(3,'KEHINDE','HARUNA',56,'1980-09-05'),
		(4,'ISLAMIYAH','ADEDIJI',34,'1770-05-01'),
		(5,'WINNER','OLAWALE',12,'1889-11-29')

  -- UPDATE--
 UPDATE  OLAWALE
    SET AGE = 43
	WHERE FIRST_NAME = 'RAJI';

	--TRUNCATE--
TRUNCATE  TABLE OLAWALE  -- REMOVE ALL THE ROWS IN THE TABLE
 -- DELETE--
 DELETE FROM  OLAWALE
  WHERE FIRST_NAME = 'RAJI' -- REMOVE THE  MATCHING ROW IN THE TABLE

DELETE FROM OLAWALE --DELETE THE TABLE

-- MERGE---
CREATE TABLE BOLA (
	ID INT PRIMARY KEY,
	FULL_NAME VARCHAR (50),
	AGE INT,
	OCCUPATION VARCHAR (50)
	)

CREATE TABLE ISM (
	ID INT PRIMARY KEY,
	FULL_NAME VARCHAR (50),
	AGE INT,
	OCCUPATION VARCHAR (50)
	)

INSERT INTO BOLA(ID,FULL_NAME,AGE,OCCUPATION)
	VALUES (1,'ADAM ISMAILA',21,'MANAGER'),
			(2, 'BOLA MAYOWA',43,'TRADER')
INSERT INTO ISM (ID,FULL_NAME,AGE,OCCUPATION)
	VALUES (3,'YEMI ISMA',71,'MANAGER'),
			(4, 'WOLE AYO',49,'TRADER')

MERGE INTO BOLA AS BO 
	 USING ISM 
    ON BO.FULL_NAME=ISM.FULL_NAME
	WHEN NOT MATCHED THEN
	INSERT (ID,FULL_NAME,AGE,OCCUPATION)
	VALUES(ISM.ID,ISM.FULL_NAME,ISM.AGE,ISM.OCCUPATION);
--- MERGE SYNTAX
	/*MERGE INTO TARGET_TABLE 
	 USING SOURCE_TABLE
	 ON TARGET_TABLE.COLUMN_NAME = SOURCE_TABLE.COLUMN_NAME
	 WHEN MATCHED THEN
	 UPDATE SET TARGET_TABLE.COLUMN_NAME= SOURCE_TABLE.COLUMN_NAME
	 WHEN NOT MATCHED THEN
	 INSERT(COLUMN_NAME,...)
	 VALUES(SOURCE_TABLE.COLUMN_NAME,...)
	 OR 
	 WHEN NOT MATCHED THEN
	 DELETE */

 --- DATA MANIPULATION LANGUAGE---
   -- UPDATE,DELETE,INSERT
   -- DELETE-
   DELETE  BOLA -- REMOVE TABLE
   TRUNCATE TABLE ISM -- REMOVE ALL THE ROWS
   DELETE ISM
   DELETE OLAWALE

-- JOIN IN SQL--
  -- INNER JOIN( BY DEFAULT),FULL JOIN, LEFT JOIN, RIGHT JOIN---
		-- LEFT JOIN --
SELECT * 
	FROM SALES.CUSTOMERS SC LEFT JOIN SALES.ORDERS SO
	ON SC.CustomerID =SO.CustomerID
	  -- RIGHT JOIN--
SELECT * 
	FROM SALES.CUSTOMERS SC RIGHT JOIN SALES.ORDERS SO
	ON SC.CustomerID =SO.CustomerID
	--- INNER JOIN--
SELECT * 
	FROM SALES.CUSTOMERS SC INNER JOIN SALES.ORDERS SO
	ON SC.CustomerID =SO.CustomerID
	 -- FULL JOIN --
SELECT * 
	FROM SALES.CUSTOMERS SC FULL JOIN SALES.ORDERS SO
	ON SC.CustomerID =SO.CustomerID
	-- LEFT ANTI JOIN--
SELECT * 
	FROM SALES.CUSTOMERS SC LEFT JOIN SALES.ORDERS SO  --- ONLY THE LEFT TABLE THAT DOESNT HAVE A MATCH IN OTHER TABLE
	ON SC.CustomerID =SO.CustomerID
	WHERE SO.CustomerID IS NULL
	-- RIGHT ANTI JOIN --
SELECT * 
	FROM SALES.CUSTOMERS SC RIGHT JOIN SALES.ORDERS SO  --- ONLY THE RIGHT TABLE THAT DOESNT HAVE A MATCH IN OTHER TABLE
	ON SC.CustomerID =SO.CustomerID
	WHERE SC.CustomerID IS NULL
	--- INNER ANTI JOIN--
SELECT * 
	FROM SALES.CUSTOMERS SC INNER JOIN SALES.ORDERS SO  ---  THE MATCHING ROW IN BOTH TABLE
	ON SC.CustomerID =SO.CustomerID
	WHERE SO.CustomerID IS  NOT NULL AND SC.CustomerID IS NOT NULL
	-- FULL ANTI JOIN --
SELECT * 
	FROM SALES.CUSTOMERS SC FULL JOIN SALES.ORDERS SO  ---  THE NOT MATCHING ROW IN BOTH TABLE
	ON SC.CustomerID =SO.CustomerID
	WHERE SO.CustomerID IS  NULL OR SC.CustomerID IS  NULL
	 ---CROSS JOIN--
SELECT * 
	FROM SALES.CUSTOMERS SC CROSS JOIN SALES.ORDERS SO  ---  
	ON SC.CustomerID =SO.CustomerID

	-- WHERE CLAUSE--
--1.COMPARISON OPERATOR
--2. SEARCH OPERATOR
--3. RANGE OPERATOR
--4.LOGICAL OPERATOR 
--5. MEMBERSHIP OPERATOR
    -- COMPARISON OPERATOR --
	 -- "=",">",">=","<=","<", =!
SELECT * 
	FROM SALES.Customers
	WHERE COUNTRY ='GERMANY'

SELECT * 
	FROM SALES.CUSTOMERS
	WHERE SCORE  > 350

	-- SEARCH OPERATOR
	-- LIKE-- 
SELECT *
	FROM SALES.CUSTOMERS
	WHERE COUNTRY LIKE 'G%' -- % FOR MORE ONE CHARACTER
SELECT *
	FROM SALES.CUSTOMERS
	WHERE COUNTRY LIKE '__A' -- _ FOR ONE CHARACTER
	-- RANGE OPERATOR
	-- BETWEEN--
SELECT *
	FROM SALES.CUSTOMERS
	WHERE SCORE   BETWEEN  350 AND 500

   --LOGICAL OPERATOR
   -- AND, OR , NOT-
SELECT * 
	FROM SALES.CUSTOMERS
	WHERE COUNTRY = 'GERMANY' OR FIRSTNAME ='JOSSEF'
SELECT * 
	FROM SALES.CUSTOMERS
	WHERE COUNTRY = 'GERMANY' AND FIRSTNAME ='JOSSEF'
SELECT * 
	FROM SALES.CUSTOMERS
	WHERE NOT Country = 'GERMANY'
	-- MEMBERSHIP OPERATOR--
	-- IN, NOT IN
SELECT * 
	FROM SALES.CUSTOMERS
	WHERE COUNTRY IN ('GERMANY','USA')
 SELECT * 
	FROM SALES.CUSTOMERS
	WHERE COUNTRY NOT IN ('GERMANY')

	 -- JOIN MULTIPLE TABLE--
SELECT *
	FROM SALES.CUSTOMERS SC LEFT JOIN SALES.Orders SO
	ON SC.CustomerID = SO.CustomerID
	LEFT JOIN SALES.OrdersArchive SOS
	ON SO.OrderID = SOS.OrderID
	LEFT JOIN SALES.Products SP
	ON SOS.ProductID =SP.ProductID

   -- UNION, UNION ALL , EXCEPT & INTERSECT --
     -- SET OPERATION COMBINE THE RESULT OF MULTIPLE QUERIES INTO SINGLE RESULT
SELECT  FIRSTNAME, LASTNAME
	 FROM SALES.Customers
	  UNION                            -- NO DUPLICATES
SELECT  FIRSTNAME, LASTNAME
	FROM SALES.Employees

SELECT  FIRSTNAME, LASTNAME
	FROM SALES.Customers
	  UNION ALL                          -- ALLOW DUPLICATES
SELECT  FIRSTNAME, LASTNAME
	FROM SALES.Employees

SELECT  FIRSTNAME, LASTNAME
   FROM SALES.Customers
	  EXCEPT                           -- RETURN THE ROW IN LEFT TABLE THAT HAS NO MATCH IN OTHER TABLE
SELECT  FIRSTNAME, LASTNAME
   FROM SALES.Employees

SELECT  FIRSTNAME, LASTNAME
   FROM SALES.Customers
	  INTERSECT                           -- RETURN THE MATCHING ROW IN THE BOTH TABLE
SELECT  FIRSTNAME, LASTNAME
   FROM SALES.Employees
	  
SELECT 
		[ProductID]
		,[OrderID]
		,[CustomerID]
		,[SalesPersonID]
		,[OrderDate]
		,[ShipDate]
		,[OrderStatus]
		,[ShipAddress]
		,[BillAddress]
		,[Quantity]
		,[Sales]
		,[CreationTime]
	FROM SALES.Orders
	UNION
SELECT 
		 [OrderID]
		,[ProductID]
		,[CustomerID]
		,[SalesPersonID]
		,[OrderDate]
		,[ShipDate]
		,[OrderStatus]
		,[ShipAddress]
		,[BillAddress]
		,[Quantity]
		,[Sales]
		,[CreationTime]
	FROM SALES.OrdersArchive
SELECT *
	FROM SALES.Products
SELECT * 
	FROM SALES.Employees
SELECT * 
	FROM SALES.Customers 



 
