--Explore all the object in the Database

Select * from INFORMATION_SCHEMA.tables

--Explore all the columns in the Database

Select * from INFORMATION_SCHEMA.COLUMNS
where Table_name = 'dim_Customers'

Select * from INFORMATION_SCHEMA.COLUMNS
where Table_name = 'dim_products'

--Explore all the countries our customers come from.
Select * from gold.dim_customers
where country is null

Use DataWarehouse

-- Eplore all the categories "The major Division"

Select 
	Distinct category,
	subcategory 
from gold.dim_products

-- Find the date of first and last order
--How many year of sales

Select 
	min(Order_date) as First_orderdate,
	Max(Order_date) as Last_orderdate,
	Datediff(year,min(Order_date),Max(Order_date)) as Year_of_sales
from gold.fact_sales

-- Find the youngest and oldest customers

Select 
	Min(DOB) as Oldest_birthdate,
	Max(DOB) as Youngest_birthdate,
	Datediff(year,min(DOB),GetDate()) as Oldest_age,
	Datediff(year,max(DOB),GetDate()) as youngest_age
from gold.dim_Customers


Select * from gold.dim_Customers
where DOB = '9999-11-20'


/* Explore the column with measure*/
--Find the total sales
Select 
	sum(sales) as total_sales
from gold.fact_sales

-- Find how many items are sold

Select 
	sum(quantity) as Total_quantity
from gold.fact_sales

--Find the average selling price
Select 
	Avg(price) as Average_selling_price
From gold.fact_sales
--Find the total number of order
Select 
	count(order_number) as total_customers
from gold.fact_sales

--Find the total number of products
Select 
	count(product_key) as total_product
From gold.dim_products
--Find the total number of customers
Select 
	count(customer_key) as total_customers
From gold.dim_Customers
 
--find total number of customesr that have placed order
Select 
	count(Distinct_customers)
from(
Select 
	Distinct (customer_key) as Distinct_customers
From gold.fact_sales)t

-- Generate  a report that all key metrics of the business
Select 'Total Sales' as measure_name, sum(sales) as measure_value from gold.fact_sales
Union all
Select 'Total Quantity',sum(quantity) from gold.fact_sales
union all
Select 'Average Price', avg(price) from gold.fact_sales
union all
Select 'Total Order', count(distinct order_number) from gold.fact_sales
union all
Select 'Total Product', count(product_key) from gold.dim_products
union all
Select 'Total Customer', count(customer_key) from gold.dim_customers


--Find the total customers by country
Select 
	country  as Country,
	count(customer_key) as total_customers
from gold.dim_Customers
group by country
order by count(customer_key) Desc

--Find total customers by gender
Select 
	gender	  as Country,
	count(customer_key) as total_customers
from gold.dim_Customers
group by gender
order by count(customer_key) Desc


--Find the total products by category
Select 
	category  as Category,
	count(product_key) as total_product
from gold.dim_products
group by category
order by count(product_key) Desc
--What is the average cost in each category

Select 
	category, 
	avg(cost) as Average_cost
from gold.dim_products 
group by category
order by avg(cost) Desc

--What is total revenue generated in each category
Select 
	p.category as Category,
	sum(c.sales) as Revenue_per_category
from gold.dim_products p left join gold.fact_sales c
on p.product_key = c.product_key
group by p.category
order by sum(c.sales) desc



--Find the total revenue generated by each customers
Select 
	p.customer_key as customers,
	p.firstname,
	p.lastname,
	sum(c.sales) as revenue_per_customers
from gold.dim_Customers p left join gold.fact_sales c
on p.customer_key = c.customer_key
group by p.customer_key,p.firstname,p.lastname
order by sum(c.sales) desc


--What is the distribution of sold items across the countries
Select 
	p.country as Country,
	sum(c.quantity) as Sold_items
from gold.dim_Customers p left join gold.fact_sales c
on p.customer_key = c.customer_key
group by p.country
order by sum(c.quantity) desc


--Which 5 products generate highest revenue?
Select 
	Top(5) p.product_key,
	p.product_name,
	sum(f.sales) as Total_revenue ,
	rank() over(order by sum(f.sales) desc) as Rank_number
from gold.dim_products p right join gold.fact_sales f
on p.product_key = f.product_key
group by p.product_key,p.product_name

--What are the 5 worst performance products in terms of sales?
Select 
	Top(5) p.product_key,
	p.product_name,
	sum(f.sales) as Total_revenue ,
	rank() over(order by sum(f.sales) ) as Rank_number
from gold.dim_products p right join gold.fact_sales f
on p.product_key = f.product_key
group by p.product_key,p.product_name

--Find the top 10 customers who generated the highest revenue
Select 
	Top(10) p.customer_key,
	p.firstname,
	p.lastname,
	sum(f.sales) as Total_revenue ,
	rank() over(order by sum(f.sales) desc ) as Rank_number
from gold.dim_customers p right join gold.fact_sales f
on p.customer_key = f.customer_key
group by p.customer_key,p.firstname,p.lastname

--The 3 customers with fewest orders placed
Select 
	top 3 p.customer_key,
	p.firstname,
	p.lastname,
	count(distinct Order_number) 
from gold.dim_Customers p right join gold.fact_sales f
on p.customer_key = f.customer_key
group by p.customer_key,p.firstname,p.lastname
order by count(f.customer_key)

--Analyze sales performance over time
Select 
	Year(order_date) as year,
	month(order_date) as month,
	sum(sales) as total_sales,
	count(distinct customer_key) as total_customers,
	sum(quantity) as total_quantity
from gold.fact_sales
where order_date is not null
Group by Year(order_date), month(order_date)
order by year(order_date), month(order_date)

Select 
	Datetrunc(year,order_date) as month,
	sum(sales) as total_sales
from gold.fact_sales
where order_date is not null
group by Datetrunc(year,order_date)
order by Datetrunc(year, order_date)

--Calculate the total sales per month and the running total of sales over time
Select
	month,
	total_sales,
	sum(total_sales) Over(order by month) as running_total
from
(Select 
	datetrunc(month,order_date) as month,
	sum(sales)  as total_sales	 
from gold.fact_sales
where order_date is not null
group by datetrunc(month,order_date)
)t

-- Year
Select
	year,
	total_sales,
	sum(total_sales) Over(order by  year) as running_total,
	Average_price,
	avg(Average_price) over(order by year) as moving_average
from
(Select 
	datetrunc(year,order_date) as year,
	sum(sales)  as total_sales	,
	avg(price) as  Average_price
from gold.fact_sales
where order_date is not null
group by datetrunc(year,order_date)
)t


---Performance Analysis

-- Analyze the year performance of products by comparing each product's sales to both
--its  Average sales performance and the previous year sales

with Yearly_Product_performance as(
Select  
	year(f.order_date) as order_date,
	p.product_name as product_name, 
	sum(f.sales) as current_sales 
	from gold.fact_sales f left join gold.dim_products p
on f.product_key = p.product_key
where f.order_date is not null
group by p.product_name,year(f.order_date))

Select 
	order_date,
	product_name,
	current_sales,
	Avg(current_sales) over(partition by product_name) as Average_Sales,
	current_sales - Avg(current_sales) over(partition by product_name) as diff_avg,
	case
		when current_sales - Avg(current_sales) over(partition by product_name) > 0 then 'Above Average'
		when current_sales - Avg(current_sales) over(partition by product_name) < 0 then 'Below Average'
		Else 'Average'
	End as Average_diff,
	lag(current_sales) over(partition by product_name order by order_date) as pervious_sales,
	current_sales - 	lag(current_sales) over(partition by product_name order by order_date) as YoY_change
from Yearly_Product_performance
order by product_name, order_date
	

							---Part-to-analysis
	-- Find the categories of product that contribute most to overall sales

with category_sales as (
Select	
	p.category ,
	sum(f.sales) as total_sales
from gold.fact_sales f left join gold.dim_products p
on f.product_key = p.product_key
group by p.category)
Select
	category,
	total_sales,
	sum(total_sales) over() as overall_sales,
	concat(round ((cast(total_sales as float)/sum(total_sales) over()*100 ),2),'%' ) as Percentage_sales
from category_sales
order by Percentage_sales desc

--Find the categories of product that contribute most to overall order
with category_sales as (
Select	
	p.category ,
	count(f.Order_number) as total_order
from gold.fact_sales f left join gold.dim_products p
on f.product_key = p.product_key
group by p.category)
Select
	category,
	total_order,
	sum(total_order) over() as overall_order,
	concat(round ((cast(total_order as float)/sum(total_order) over()*100 ),2),'%' ) as Percentage_sales
from category_sales
order by total_order desc

--Find the categories of product that contribute most to overall quantity
with category_quantity as (
Select	
	p.category ,
	sum(f.quantity) as total_quantity
from gold.fact_sales f left join gold.dim_products p
on f.product_key = p.product_key
group by p.category)
Select
	category,
	total_quantity,
	sum(total_quantity) over() as overall_sales,
	concat(round ((cast(total_quantity as float)/sum(total_quantity) over()*100 ),2),'%' ) as Percentage_quantity
from category_quantity
order by total_quantity desc

-- Data segmentation
-- Segment products into cost ranges and count how many product falls into each segment
with segmented_cost as(
Select 
	product_key,
	product_name,
	cost,
	case
		when cost < 100 then 'Below 100'
		when cost between 100 and 500 then '100 - 500'
		when cost between 500 and 1000 then '500 - 1000'
		else 'Above 1000'
	End cost_segment
from gold.dim_products)

Select
	cost_segment,
	count(product_key) as product_count
from segmented_cost
group by cost_segment
order by product_count desc

Use Datawarehouse

-- Task
/*Group customers into three segment based on their spending behaviour:
Vip: at least 12 month of history and spending more than $5000
Regular: at least 12 month of history but spending $5000 or less
New:lifespan less 12 month
and the total number of customer by each group*/
With customers_segment as (
Select
	c.customer_key,
	sum(f.sales) as total_sales,
	min(f.order_date) as first_date,
	max(f.order_date) as last_date,
	datediff(month,min(f.order_date),max(f.order_date)) as life_span
from gold.fact_sales f left join gold.dim_customers c
on f.customer_key = c.customer_key
group by c.customer_key)

Select 
	Spending_behaviour,
	count(customer_key) as total_customer
from
(Select 
	customer_key,
	case	
		when life_span >= 12 and total_sales > 5000 then 'VIP'
		when life_span >= 12 and total_sales <= 5000 then 'Regular'
		else'New'
	End as Spending_behaviour
from customers_segment)t
group by Spending_behaviour
order by total_customer desc
/*
============================================================================================================================
Customers report

============================================================================================================================
purpose:
	This report consolidate key customers metrics and behaviour

Highligth:
	1. Gather important field such names, age and transactional details
	2.Segment customers into categories (VIP, Regular and New) and Age group
	3.Aggregate customers level metrics:
		- total orders
		- total sales
		- total product 
		- total quantity purchased
	Calculate Valuable KPIs:
		- recency (since last order)
		- average order value
		- average monthly spend

============================================================================================================================
*/
Create or alter view gold.customers_table as 
with base_query as (
Select 
--===========================================================================================================================
--Purpose: to retrieve core table column

--==========================================================================================================================
	f.order_number,
	f.product_key,
	f.order_date,
	f.sales,
	f.quantity,
	c.customer_key,
	c.customer_number,
	concat(c.firstname,' ', c.lastname) as fullname,
	c.DOB,
	datediff(year,c.DOB,getdate()) as customer_age
from gold.fact_sales f left join gold.dim_Customers c
on f.customer_key = c.customer_key 
where order_date is not null)

, customer_agggregate as (

Select 
	customer_key,
	customer_number,
	fullname,
	customer_age,															--Customer_aggregate
	count(distinct Order_number) as total_order,
	count(distinct product_key) as total_product,
	sum(sales) as total_sales,
	sum(quantity) as total_quantity_purchased,
	max(order_date) as last_date,
	min(order_date) as first_date,
	datediff(month,min(order_date),max(order_date)) as life_span
from base_query
group by customer_key,customer_number,fullname,customer_age)

Select 
	customer_key,
	customer_number,
	fullname,
	customer_age,
	case
		when customer_age < 20 then 'Below 20'
		when customer_age between 20 and 29 then '20 - 29'
		when customer_age between 30 and 39 then '30 - 39'
		when customer_age between 40 and 49 then '40 - 49'
		else 'Above 50'
	end as age_group,
	total_order,
	total_product,
	total_quantity_purchased,
	total_sales,
	life_span,
	case
		when life_span >= 12 and total_sales > 5000  then 'VIP'
		when life_span >= 12 and total_sales <= 5000 then 'Regular'
		else 'New'
	end as customer_badge,
	last_date,
	datediff(month,last_date,getdate()) as recency,
	case 
		when total_order = 0 then total_sales
		else total_sales/total_order 
	end as average_order_value,
	case
		when life_span = 0 then total_sales
		else total_sales/life_span 
	end as average_monthly_spend
from customer_agggregate 
	
--=============================================================================================================
	---Querying the table
--==============================================================================================
	Select * from gold.customers_table

